// Generated by Dagger (https://dagger.dev).
package com.hilt.hiltandroid.dagger.modules.car;

import dagger.internal.Factory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class Remote_Factory implements Factory<Remote> {
  @Override
  public Remote get() {
    return newInstance();
  }

  public static Remote_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static Remote newInstance() {
    return new Remote();
  }

  private static final class InstanceHolder {
    private static final Remote_Factory INSTANCE = new Remote_Factory();
  }
}
