// Generated by Dagger (https://dagger.dev).
package com.hilt.hiltandroid.dagger.modules.engine;

import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DieselEngine_Factory implements Factory<DieselEngine> {
  private final Provider<Integer> horsepowerProvider;

  public DieselEngine_Factory(Provider<Integer> horsepowerProvider) {
    this.horsepowerProvider = horsepowerProvider;
  }

  @Override
  public DieselEngine get() {
    return newInstance(horsepowerProvider.get());
  }

  public static DieselEngine_Factory create(Provider<Integer> horsepowerProvider) {
    return new DieselEngine_Factory(horsepowerProvider);
  }

  public static DieselEngine newInstance(int horsepower) {
    return new DieselEngine(horsepower);
  }
}
