// Generated by Dagger (https://dagger.dev).
package com.hilt.hiltandroid.dagger.modules.modules;

import dagger.internal.Factory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DieselEngineModule_ProvideHorsePowerFactory implements Factory<Integer> {
  private final DieselEngineModule module;

  public DieselEngineModule_ProvideHorsePowerFactory(DieselEngineModule module) {
    this.module = module;
  }

  @Override
  public Integer get() {
    return provideHorsePower(module);
  }

  public static DieselEngineModule_ProvideHorsePowerFactory create(DieselEngineModule module) {
    return new DieselEngineModule_ProvideHorsePowerFactory(module);
  }

  public static int provideHorsePower(DieselEngineModule instance) {
    return instance.provideHorsePower();
  }
}
